version: '3'
services:
  backend:
    build: 
      context: backend 
      dockerfile: backend.Dockerfile
    ports:
     - "5000:5000"
  db:
    image: "redis:alpine"
  frontend:
    build: 
      context: frontend
      dockerfile: frontend.Dockerfile
    ports:
     - "8090:8090"
    depends_on:
     - backend 

